# Generated by Django 4.2 on 2023-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='music',
            field=models.CharField(default='Eli', max_length=50, verbose_name='Музичний супровід'),
        ),
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.CharField(default='Eli', max_length=50, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='video',
            name='vocal',
            field=models.CharField(default='Eli', max_length=50, verbose_name='Вокал'),
        ),
    ]
