# Generated by Django 4.2 on 2023-05-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.collaborator')),
            ],
        ),
    ]
